version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_KEY=AIzaSyB79JEAKXWCXYgpQ8AzHc5QJW8fMitrDwM
      - REACT_APP_AUTH_DOMAIN=react-auth-cc626.firebaseapp.com
      - REACT_APP_PROJECT_ID=react-auth-cc626
      - REACT_APP_STORAGE_BUCKET=react-auth-cc626.appspot.com
      - REACT_APP_MESSAGING_SENDER_ID=509512222694
      - REACT_APP_APP_ID=1:509512222694:web:47e8b94e4e3ed75ae9b827
    volumes:
      - .:/app
